export type DuaSection = "morning_evening" | "salah" | "quranic" | "occasion";

export interface Dua {
  id: number;
  section: DuaSection;
  title: { en: string; ur: string };
  arabic: string;
  translation: { en: string; ur: string };
  reference?: string;
}

export const DUA_SECTIONS: { key: DuaSection; en: string; ur: string; icon: string }[] = [
  { key: "morning_evening", en: "Morning & Evening", ur: "صبح و شام",       icon: "🌅" },
  { key: "salah",           en: "Salah Duas",        ur: "نماز کی دعائیں",  icon: "🕌" },
  { key: "quranic",         en: "Quranic Duas",      ur: "قرآنی دعائیں",     icon: "📖" },
  { key: "occasion",        en: "Special Occasions", ur: "خاص مواقع",       icon: "✨" },
];

export const DUAS: Dua[] = [
  // ── Morning & Evening ────────────────────────────────────────────
  { id: 1,  section: "morning_evening",
    title: { en: "Bismillah", ur: "بسم اللہ" },
    arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    translation: {
      en: "In the name of Allah, the Most Gracious, the Most Merciful.",
      ur: "اللہ کے نام سے جو بڑا مہربان اور نہایت رحم والا ہے۔",
    },
  },
  { id: 2,  section: "morning_evening",
    title: { en: "Hamd", ur: "حمد" },
    arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    translation: {
      en: "All praise is due to Allah, Lord of the worlds.",
      ur: "سب تعریف اللہ کے لیے ہے جو تمام جہانوں کا پالنے والا ہے۔",
    },
  },
  { id: 3,  section: "morning_evening",
    title: { en: "Ta'awwudh", ur: "تعوذ" },
    arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    translation: {
      en: "I seek refuge with Allah from the accursed Satan.",
      ur: "میں اللہ کی پناہ مانگتا ہوں شیطان مردود سے۔",
    },
  },
  { id: 4,  section: "morning_evening",
    title: { en: "Tasbeeh", ur: "تسبیح" },
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    translation: {
      en: "Glory be to Allah and praise Him.",
      ur: "اللہ پاک ہے اور اسی کی تعریف ہے۔",
    },
  },
  { id: 5,  section: "morning_evening",
    title: { en: "Tahleel", ur: "تہلیل" },
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ",
    translation: {
      en: "There is no god but Allah.",
      ur: "اللہ کے سوا کوئی معبود نہیں۔",
    },
  },
  { id: 6,  section: "morning_evening",
    title: { en: "Takbeer", ur: "تکبیر" },
    arabic: "اللَّهُ أَكْبَرُ",
    translation: {
      en: "Allah is the Greatest.",
      ur: "اللہ سب سے بڑا ہے۔",
    },
  },
  { id: 7,  section: "morning_evening",
    title: { en: "Istighfar", ur: "استغفار" },
    arabic: "أَسْتَغْفِرُ اللَّهَ",
    translation: {
      en: "I seek forgiveness from Allah.",
      ur: "میں اللہ سے مغفرت مانگتا ہوں۔",
    },
  },
  { id: 8,  section: "morning_evening",
    title: { en: "Hasbiyallah", ur: "حسبی اللہ" },
    arabic: "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ",
    translation: {
      en: "Allah is sufficient for me; there is no god but He.",
      ur: "اللہ میرے لیے کافی ہے، اس کے سوا کوئی معبود نہیں۔",
    },
  },
  { id: 9,  section: "morning_evening",
    title: { en: "Durood", ur: "درود" },
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
    translation: {
      en: "O Allah, send blessings upon Muhammad and the family of Muhammad.",
      ur: "اے اللہ، محمد اور آلِ محمد پر رحمت نازل فرما۔",
    },
  },
  { id: 10, section: "morning_evening",
    title: { en: "Rabbana Atina", ur: "ربنا آتنا" },
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    translation: {
      en: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
      ur: "ہمارے رب، ہمیں دنیا میں بھلائی دے اور آخرت میں بھلائی دے اور ہمیں آگ کے عذاب سے بچا۔",
    },
    reference: "Qur'an 2:201",
  },

  // ── Salah Duas ──────────────────────────────────────────────────
  { id: 11, section: "salah",
    title: { en: "Takbeer (Starting Prayer)", ur: "تکبیرِ تحریمہ" },
    arabic: "اللَّهُ أَكْبَرُ",
    translation: {
      en: "Allah is the Greatest.",
      ur: "اللہ سب سے بڑا ہے۔",
    },
  },
  { id: 12, section: "salah",
    title: { en: "Dua of Ruku", ur: "رکوع کی دعا" },
    arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
    translation: {
      en: "Glory be to my Lord, the Almighty.",
      ur: "میں اپنے عظیم رب کی پاکی بیان کرتا ہوں۔",
    },
  },
  { id: 13, section: "salah",
    title: { en: "Dua of Sujud", ur: "سجدہ کی دعا" },
    arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
    translation: {
      en: "Glory be to my Lord, the Most High.",
      ur: "میں اپنے بلند ترین رب کی پاکی بیان کرتا ہوں۔",
    },
  },
  { id: 14, section: "salah",
    title: { en: "Between Two Sujuds", ur: "دو سجدوں کے درمیان" },
    arabic: "رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي",
    translation: {
      en: "My Lord, forgive me; my Lord, forgive me.",
      ur: "میرے رب، مجھے بخش دے؛ میرے رب، مجھے بخش دے۔",
    },
  },
  { id: 15, section: "salah",
    title: { en: "Tashahhud", ur: "تشہد" },
    arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ",
    translation: {
      en: "All greetings, prayers and good things are for Allah.",
      ur: "تمام تحیات، نمازیں اور پاکیزہ چیزیں اللہ کے لیے ہیں۔",
    },
  },
  { id: 16, section: "salah",
    title: { en: "Durood Ibrahim", ur: "درود ابراہیمی" },
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ",
    translation: {
      en: "O Allah, send blessings upon Muhammad and his family as You sent blessings upon Ibrahim.",
      ur: "اے اللہ، محمد اور آلِ محمد پر رحمت نازل فرما جیسے تو نے ابراہیم پر فرمائی۔",
    },
  },
  { id: 17, section: "salah",
    title: { en: "After Tashahhud", ur: "تشہد کے بعد" },
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ",
    translation: {
      en: "O Allah, I seek refuge with You from the punishment of the grave.",
      ur: "اے اللہ، میں قبر کے عذاب سے تیری پناہ مانگتا ہوں۔",
    },
  },
  { id: 18, section: "salah",
    title: { en: "Dua Qunoot", ur: "دعائے قنوت" },
    arabic: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ وَعَافِنِي فِيمَنْ عَافَيْتَ",
    translation: {
      en: "O Allah, guide me among those You have guided and grant me well-being among those You have granted well-being.",
      ur: "اے اللہ، مجھے ان لوگوں کے ساتھ ہدایت دے جنہیں تو نے ہدایت دی اور ان کے ساتھ عافیت دے جنہیں تو نے عافیت دی۔",
    },
  },
  { id: 19, section: "salah",
    title: { en: "Salam (End of Prayer)", ur: "سلام" },
    arabic: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
    translation: {
      en: "Peace be upon you and Allah's mercy.",
      ur: "تم پر سلامتی ہو اور اللہ کی رحمت ہو۔",
    },
  },
  { id: 20, section: "salah",
    title: { en: "After Salah Tasbeeh", ur: "نماز بعد تسبیح" },
    arabic: "سُبْحَانَ اللَّهِ، الْحَمْدُ لِلَّهِ، اللَّهُ أَكْبَرُ",
    translation: {
      en: "Glory be to Allah, all praise to Allah, Allah is the Greatest.",
      ur: "اللہ پاک ہے، تمام تعریف اللہ کے لیے ہے، اللہ سب سے بڑا ہے۔",
    },
  },

  // ── Quranic Duas ────────────────────────────────────────────────
  { id: 21, section: "quranic",
    title: { en: "Guide us to the Straight Path", ur: "سیدھا راستہ" },
    arabic: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
    translation: {
      en: "Guide us to the straight path.",
      ur: "ہمیں سیدھا راستہ دکھا۔",
    },
    reference: "Al-Fatiha 1:6",
  },
  { id: 22, section: "quranic",
    title: { en: "Accept From Us", ur: "ہم سے قبول فرما" },
    arabic: "رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ",
    translation: {
      en: "Our Lord, accept from us. Indeed, You are the All-Hearing, the All-Knowing.",
      ur: "ہمارے رب، ہم سے قبول فرما۔ بے شک تو سننے والا، جاننے والا ہے۔",
    },
    reference: "Al-Baqarah 2:127",
  },
  { id: 23, section: "quranic",
    title: { en: "Steady Our Hearts", ur: "دلوں کو ٹیڑھا نہ کر" },
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا",
    translation: {
      en: "Our Lord, do not let our hearts deviate after You have guided us.",
      ur: "ہمارے رب، ہدایت دینے کے بعد ہمارے دلوں کو ٹیڑھا نہ کر۔",
    },
    reference: "Aal-e-Imran 3:8",
  },
  { id: 24, section: "quranic",
    title: { en: "Forgive Our Sins", ur: "گناہ معاف فرما" },
    arabic: "رَبَّنَا فَاغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا",
    translation: {
      en: "Our Lord, forgive us our sins and remove our misdeeds.",
      ur: "ہمارے رب، ہمارے گناہ معاف فرما اور ہماری برائیاں دور فرما۔",
    },
    reference: "Aal-e-Imran 3:193",
  },
  { id: 25, section: "quranic",
    title: { en: "Establisher of Prayer", ur: "نماز قائم کرنے والا" },
    arabic: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِنْ ذُرِّيَّتِي",
    translation: {
      en: "My Lord, make me an establisher of prayer, and from my descendants too.",
      ur: "میرے رب، مجھے اور میری اولاد کو نماز قائم کرنے والا بنا۔",
    },
    reference: "Ibrahim 14:40",
  },
  { id: 26, section: "quranic",
    title: { en: "Forgive Parents", ur: "والدین کو بخش دے" },
    arabic: "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
    translation: {
      en: "Our Lord, forgive me, my parents and the believers on the Day the account is established.",
      ur: "ہمارے رب، مجھے، میرے والدین کو اور تمام ایمان والوں کو حساب کے دن بخش دے۔",
    },
    reference: "Ibrahim 14:41",
  },
  { id: 27, section: "quranic",
    title: { en: "Mercy From Yourself", ur: "اپنی رحمت دے" },
    arabic: "رَبَّنَا آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا",
    translation: {
      en: "Our Lord, grant us mercy from Yourself and prepare for us right guidance in our affair.",
      ur: "ہمارے رب، ہمیں اپنی طرف سے رحمت دے اور ہمارے کام میں ہمارے لیے رہنمائی آسان فرما۔",
    },
    reference: "Al-Kahf 18:10",
  },
  { id: 28, section: "quranic",
    title: { en: "Open My Chest", ur: "میرا سینہ کھول دے" },
    arabic: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    translation: {
      en: "My Lord, expand my chest for me and ease my task for me.",
      ur: "میرے رب، میرا سینہ کھول دے اور میرا کام آسان فرما۔",
    },
    reference: "Taha 20:25-26",
  },
  { id: 29, section: "quranic",
    title: { en: "Increase Me in Knowledge", ur: "علم میں اضافہ" },
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    translation: {
      en: "My Lord, increase me in knowledge.",
      ur: "میرے رب، میرے علم میں اضافہ فرما۔",
    },
    reference: "Taha 20:114",
  },
  { id: 30, section: "quranic",
    title: { en: "Honorable Entrance", ur: "سچائی سے داخل کر" },
    arabic: "رَبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ",
    translation: {
      en: "My Lord, admit me with an honorable entrance and remove me with an honorable exit.",
      ur: "میرے رب، مجھے سچائی کے ساتھ داخل کر اور سچائی کے ساتھ نکال۔",
    },
    reference: "Al-Isra 17:80",
  },

  // ── Special Occasion Duas ───────────────────────────────────────
  { id: 31, section: "occasion",
    title: { en: "Entering the Masjid", ur: "مسجد میں داخل ہونے کی دعا" },
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    translation: {
      en: "O Allah, open for me the doors of Your mercy.",
      ur: "اے اللہ، میرے لیے اپنی رحمت کے دروازے کھول۔",
    },
  },
  { id: 32, section: "occasion",
    title: { en: "Leaving the Masjid", ur: "مسجد سے نکلنے کی دعا" },
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    translation: {
      en: "O Allah, I ask You of Your bounty.",
      ur: "اے اللہ، میں تجھ سے تیرے فضل کا سوال کرتا ہوں۔",
    },
  },
  { id: 33, section: "occasion",
    title: { en: "Before Eating", ur: "کھانے سے پہلے" },
    arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ",
    translation: {
      en: "In the name of Allah and upon the blessings of Allah.",
      ur: "اللہ کے نام پر اور اللہ کی برکت سے۔",
    },
  },
  { id: 34, section: "occasion",
    title: { en: "After Eating", ur: "کھانے کے بعد" },
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ",
    translation: {
      en: "Praise be to Allah who fed me this and provided it to me.",
      ur: "تمام تعریف اس اللہ کے لیے ہے جس نے مجھے یہ کھلایا اور اس کا رزق دیا۔",
    },
  },
  { id: 35, section: "occasion",
    title: { en: "When Sneezing", ur: "چھینکنے پر" },
    arabic: "الْحَمْدُ لِلَّهِ",
    translation: {
      en: "Praise be to Allah.",
      ur: "تمام تعریف اللہ کے لیے ہے۔",
    },
  },
  { id: 36, section: "occasion",
    title: { en: "Response to Sneeze", ur: "چھینک کا جواب" },
    arabic: "يَرْحَمُكَ اللَّهُ",
    translation: {
      en: "May Allah have mercy on you.",
      ur: "اللہ تم پر رحم کرے۔",
    },
  },
  { id: 37, section: "occasion",
    title: { en: "Entering Home", ur: "گھر میں داخل ہونے کی دعا" },
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ",
    translation: {
      en: "O Allah, I ask You for the best of entries and the best of exits.",
      ur: "اے اللہ، میں تجھ سے بہترین داخلے اور بہترین خروج کا سوال کرتا ہوں۔",
    },
  },
  { id: 38, section: "occasion",
    title: { en: "Leaving Home", ur: "گھر سے نکلنے کی دعا" },
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    translation: {
      en: "In the name of Allah, I trust in Allah; there is no might or power except with Allah.",
      ur: "اللہ کے نام پر، میں نے اللہ پر بھروسہ کیا؛ اللہ کے سوا کوئی طاقت نہیں۔",
    },
  },
  { id: 39, section: "occasion",
    title: { en: "Visiting the Sick", ur: "بیمار کی عیادت" },
    arabic: "أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ",
    translation: {
      en: "I ask Allah, the Mighty, Lord of the Mighty Throne, to cure you.",
      ur: "میں اللہ عظیم سے، جو عظیم عرش کا رب ہے، دعا کرتا ہوں کہ وہ تمہیں شفا دے۔",
    },
  },
  { id: 40, section: "occasion",
    title: { en: "Dua for Parents", ur: "والدین کے لیے دعا" },
    arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    translation: {
      en: "My Lord, have mercy on them as they brought me up when I was small.",
      ur: "میرے رب، ان پر رحم فرما جیسا انہوں نے مجھے بچپن میں پالا۔",
    },
    reference: "Al-Isra 17:24",
  },
  { id: 41, section: "occasion",
    title: { en: "Before Sleeping", ur: "سونے سے پہلے" },
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    translation: {
      en: "In Your name, O Allah, I die and I live.",
      ur: "اے اللہ، تیرے ہی نام سے میں مرتا ہوں اور جیتا ہوں۔",
    },
  },
  { id: 42, section: "occasion",
    title: { en: "Upon Waking", ur: "بیدار ہونے پر" },
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    translation: {
      en: "Praise be to Allah who gave us life after death, and to Him is the resurrection.",
      ur: "تمام تعریف اللہ کے لیے ہے جس نے ہمیں موت کے بعد زندگی دی، اور اسی کی طرف لوٹنا ہے۔",
    },
  },
  { id: 43, section: "occasion",
    title: { en: "Travel Dua", ur: "سفر کی دعا" },
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ",
    translation: {
      en: "Glory to Him who has subjected this to us, and we could never have it by our efforts.",
      ur: "پاک ہے وہ جس نے اسے ہمارے لیے مسخر کیا، ہم اسے قابو میں نہیں کر سکتے تھے۔",
    },
    reference: "Az-Zukhruf 43:13",
  },
  { id: 44, section: "occasion",
    title: { en: "Drinking Water", ur: "پانی پینے کی دعا" },
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي جَعَلَهُ عَذْبًا فُرَاتًا بِرَحْمَتِهِ",
    translation: {
      en: "Praise be to Allah who made it sweet and refreshing by His mercy.",
      ur: "تمام تعریف اللہ کے لیے ہے جس نے اپنی رحمت سے اسے میٹھا اور صاف بنایا۔",
    },
  },
  { id: 45, section: "occasion",
    title: { en: "Seeking Forgiveness (Sayyidul Istighfar)", ur: "سیدالاستغفار" },
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    translation: {
      en: "O Allah, You are my Lord; there is no god but You. You created me and I am Your servant.",
      ur: "اے اللہ، تو میرا رب ہے، تیرے سوا کوئی معبود نہیں۔ تو نے مجھے پیدا کیا اور میں تیرا بندہ ہوں۔",
    },
    reference: "Sahih Bukhari 6306",
  },
];
